/*
* generated by Xtext
*/
package no.hib.dpf.text.ui.labeling;

import no.hib.dpf.text.tdpf.Arrow;
import no.hib.dpf.text.tdpf.Model;
import no.hib.dpf.text.tdpf.Node;
import no.hib.dpf.text.tdpf.TGraph;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class DPFTextLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public DPFTextLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
		
	String text(Model m) {
		  return "Model";
	}

	String text(TGraph n) {
	  return "Graph<" + n.getTypeGraph().getId()+">";
	}
		
	String image(Node n) {
		  return "node.png";
	}

	String image(Arrow a) {
		  return "arrow.png";
	}	

	String image(TGraph g) {
		  return "graph.png";
	}

}
