/*
* generated by Xtext
*/
package no.hib.dpf.text.ui.labeling;

import no.hib.dpf.text.tdpf.*;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class DPFTextLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public DPFTextLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
	
	
	String text(Model m) {
		  return "Model";
	}

	String text(Node n) {
		  return "";
	}

	String text(Arrow a) {
		  return "";
	}

	String image(Node n) {
		  return "node.png";
	}

	String image(Arrow a) {
		  return "arrow.png";
	}	

}
