/*
 * generated by Xtext
 */
package no.hib.dpf.text;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DPFTextRuntimeModule extends no.hib.dpf.text.AbstractDPFTextRuntimeModule {

}
