<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core"
    nsURI="http://no.hib.dpf.core" nsPrefix="core">
  <eClassifiers xsi:type="ecore:EClass" name="Specification">
    <eOperations name="createGraph" eType="#//Graph">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createConstraint" eType="#//Constraint">
      <eParameters name="predicate" lowerBound="1" eType="#//Predicate"/>
      <eParameters name="parameters" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="mapping" lowerBound="1" eType="#//GraphHomomorphism"/>
      <eParameters name="stuckedNodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="stuckedArrows" upperBound="-1" eType="#//Arrow"/>
      <eParameters name="typeNodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="typeArrows" upperBound="-1" eType="#//Arrow"/>
    </eOperations>
    <eOperations name="validate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="#//Graph"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signatureFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" eType="#//Signature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Specification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Graph" eSuperTypes="#//IDObject">
    <eOperations name="createNode" eType="#//Node">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getGraphMember" eType="#//IDObject">
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createArrow" eType="#//Arrow">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="source" eType="#//Node"/>
      <eParameters name="target" eType="#//Node"/>
    </eOperations>
    <eOperations name="applyPredicate" eType="#//Constraint">
      <eParameters name="predicate" eType="#//Predicate"/>
      <eParameters name="nodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="edges" upperBound="-1" eType="#//Arrow"/>
    </eOperations>
    <eOperations name="deleteNode">
      <eParameters name="node" eType="#//Node"/>
    </eOperations>
    <eOperations name="deleteArrow">
      <eParameters name="edge" eType="#//Arrow"/>
    </eOperations>
    <eOperations name="getNodeByName" eType="#//Node">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getArrowByName" eType="#//Arrow">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createNode" eType="#//Node">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="typeNode" eType="#//Node"/>
    </eOperations>
    <eOperations name="createArrow" eType="#//Arrow">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="source" eType="#//Node"/>
      <eParameters name="target" eType="#//Node"/>
      <eParameters name="typeEdge" eType="#//Arrow"/>
    </eOperations>
    <eOperations name="extractSubgraph" eType="#//Graph">
      <eParameters name="nodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="arrows" upperBound="-1" eType="#//Arrow"/>
    </eOperations>
    <eOperations name="getNodesForConstraint" upperBound="-1" eType="#//Node">
      <eParameters name="constraint" eType="#//Constraint"/>
    </eOperations>
    <eOperations name="getArrowsForConstraint" upperBound="-1" eType="#//Arrow">
      <eParameters name="constraint" eType="#//Constraint"/>
    </eOperations>
    <eOperations name="getNodes" upperBound="-1" eType="#//Node">
      <eParameters name="typeNodes" upperBound="-1" eType="#//Node"/>
    </eOperations>
    <eOperations name="getArrows" upperBound="-1" eType="#//Arrow">
      <eParameters name="types" upperBound="-1" eType="#//Arrow"/>
    </eOperations>
    <eOperations name="getCopy" eType="#//Graph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Graph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrows" upperBound="-1"
        eType="#//Arrow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//IDObject">
    <eOperations name="arrowCanMakeConnectionAsTarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="intendedTarget" eType="#//Node"/>
    </eOperations>
    <eOperations name="canReachTargetByOneArrow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="target" eType="#//Node"/>
    </eOperations>
    <eOperations name="arrowCanMakeConnectionAsTarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="intendedTarget" eType="#//Node"/>
      <eParameters name="typeEdge" eType="#//Arrow"/>
    </eOperations>
    <eOperations name="canReachTargetByTypeArrow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="target" eType="#//Node"/>
      <eParameters name="typeEdge" eType="#//Arrow"/>
    </eOperations>
    <eOperations name="getArrowto" eType="#//Arrow">
      <eParameters name="target" eType="#//Node"/>
    </eOperations>
    <eOperations name="getTypeName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="generateUniqueName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="canCreateTypedArrow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="intendedTarget" eType="#//Node"/>
    </eOperations>
    <eOperations name="getTypeArrow" eType="#//Arrow">
      <eParameters name="intendedTarget" eType="#//Node"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeNode" lowerBound="1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoings" upperBound="-1"
        eType="#//Arrow" eOpposite="#//Arrow/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomings" upperBound="-1"
        eType="#//Arrow" eOpposite="#//Arrow/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" eOpposite="#//Constraint/nodes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arrow" eSuperTypes="#//IDObject">
    <eOperations name="getTypeName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="generateUniqueName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Node"
        eOpposite="#//Node/outgoings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Node"
        eOpposite="#//Node/incomings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeArrow" lowerBound="1"
        eType="#//Arrow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" eOpposite="#//Constraint/arrows"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signature">
    <eOperations name="getPredicateBySymbol" eType="#//Predicate">
      <eParameters name="symbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addPredicate">
      <eParameters name="dPredicate" eType="#//Predicate"/>
    </eOperations>
    <eOperations name="removePredicate">
      <eParameters name="dPredicate" eType="#//Predicate"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicates" upperBound="-1"
        eType="#//Predicate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Predicate">
    <eOperations name="createConstraint" eType="#//Constraint">
      <eParameters name="nodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="arrows" upperBound="-1" eType="#//Arrow"/>
      <eParameters name="modelToBeConstrained" eType="#//Graph"/>
    </eOperations>
    <eOperations name="canCreateConstraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="nodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="arrows" upperBound="-1" eType="#//Arrow"/>
      <eParameters name="modelToBeConstrained" eType="#//Graph"/>
    </eOperations>
    <eOperations name="validateSemantics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="parameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="mapping" eType="#//GraphHomomorphism"/>
      <eParameters name="graph" eType="#//Graph"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shape" eType="#//Graph"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validator" eType="#//SemanticValidator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticValidator">
    <eOperations name="validateSemantics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="constraintParameters" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="typeNodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="typeArrows" upperBound="-1" eType="#//Arrow"/>
      <eParameters name="stuckedNodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="stuckedArrows" upperBound="-1" eType="#//Arrow"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ValidatorType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" eSuperTypes="#//IDObject">
    <eOperations name="reconnect">
      <eParameters name="nodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="arrows" upperBound="-1" eType="#//Arrow"/>
      <eParameters name="specification" eType="#//Specification"/>
    </eOperations>
    <eOperations name="disconnect"/>
    <eOperations name="addArrow">
      <eParameters name="arrow" eType="#//Arrow"/>
    </eOperations>
    <eOperations name="addNode">
      <eParameters name="node" eType="#//Node"/>
    </eOperations>
    <eOperations name="validate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="graph" eType="#//Graph"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" eOpposite="#//Node/constraints"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrows" upperBound="-1"
        eType="#//Arrow" eOpposite="#//Arrow/constraints"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" eType="#//Predicate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" eType="#//GraphHomomorphism"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphHomomorphism">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeMapping" upperBound="-1"
        eType="#//NodeToNodeMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrowMapping" upperBound="-1"
        eType="#//ArrowToArrowMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeToNodeMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrowToArrowMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//Arrow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Arrow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDObject" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EResourceSet" instanceClassName="org.eclipse.emf.ecore.resource.ResourceSet"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ValidatorType">
    <eLiterals name="OCL"/>
    <eLiterals name="JAVA" value="1"/>
  </eClassifiers>
</ecore:EPackage>
