<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core" nsURI="http://no.hib.dpf.core" nsPrefix="core">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Specification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="#//Graph"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" eType="#//Signature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Specification"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metalevel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Graph" eSuperTypes="#//IDObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Graph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrows" upperBound="-1"
        eType="#//Arrow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datanodes" upperBound="-1"
        eType="#//DataNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrowAttributes" upperBound="-1"
        eType="#//ArrowAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeAttributes" upperBound="-1"
        eType="#//NodeAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//IDObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoings" upperBound="-1"
        eType="#//Arrow" eOpposite="#//Arrow/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomings" upperBound="-1"
        eType="#//Arrow" eOpposite="#//Arrow/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" eOpposite="#//Constraint/nodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeNode" lowerBound="1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingAttributes" upperBound="-1"
        eType="#//NodeAttribute" eOpposite="#//NodeAttribute/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arrow" eSuperTypes="#//IDObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/outgoings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/incomings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" eOpposite="#//Constraint/arrows"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeArrow" lowerBound="1"
        eType="#//Arrow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingAttributes" upperBound="-1"
        eType="#//ArrowAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signature">
    <eOperations name="getPredicateBySymbol" eType="#//Predicate">
      <eParameters name="symbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addPredicate">
      <eParameters name="dPredicate" eType="#//Predicate"/>
    </eOperations>
    <eOperations name="removePredicate">
      <eParameters name="dPredicate" eType="#//Predicate"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicates" upperBound="-1"
        eType="#//Predicate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Predicate">
    <eOperations name="createConstraint" eType="#//Constraint">
      <eParameters name="nodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="arrows" upperBound="-1" eType="#//Arrow"/>
    </eOperations>
    <eOperations name="canCreateConstraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="nodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="arrows" upperBound="-1" eType="#//Arrow"/>
      <eParameters name="modelToBeConstrained" eType="#//Graph"/>
    </eOperations>
    <eOperations name="validateSemantics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="parameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="mapping" eType="#//GraphHomomorphism"/>
      <eParameters name="graph" eType="#//Graph"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shape" eType="#//Graph"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validator" eType="#//SemanticValidator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticValidator">
    <eOperations name="validateSemantics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="constraintParameters" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="typeNodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="typeArrows" upperBound="-1" eType="#//Arrow"/>
      <eParameters name="stuckedNodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="stuckedArrows" upperBound="-1" eType="#//Arrow"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ValidatorType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" eSuperTypes="#//IDObject">
    <eOperations name="reconnect">
      <eParameters name="nodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="arrows" upperBound="-1" eType="#//Arrow"/>
      <eParameters name="specification" eType="#//Specification"/>
    </eOperations>
    <eOperations name="disconnect"/>
    <eOperations name="addArrow">
      <eParameters name="arrow" eType="#//Arrow"/>
    </eOperations>
    <eOperations name="addNode">
      <eParameters name="node" eType="#//Node"/>
    </eOperations>
    <eOperations name="validate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="graph" eType="#//Graph"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" eOpposite="#//Node/constraints"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrows" upperBound="-1"
        eType="#//Arrow" eOpposite="#//Arrow/constraints"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" eType="#//Predicate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" eType="#//GraphHomomorphism"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrowAttributes" upperBound="-1"
        eType="#//ArrowAttribute" eOpposite="#//ArrowAttribute/constraints"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeAttributes" upperBound="-1"
        eType="#//NodeAttribute" eOpposite="#//NodeAttribute/constraints"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphHomomorphism">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeMapping" upperBound="-1"
        eType="#//NodeToNodeMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrowMapping" upperBound="-1"
        eType="#//ArrowToArrowMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeToNodeMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrowToArrowMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//Arrow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Arrow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IDObject" abstract="true" eSuperTypes="#//DeepElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EResourceSet" instanceClassName="org.eclipse.emf.ecore.resource.ResourceSet"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ValidatorType">
    <eLiterals name="OCL"/>
    <eLiterals name="JAVA" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeepElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mutability" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="potency" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingNodeAttributes"
        upperBound="-1" eType="#//NodeAttribute" eOpposite="#//NodeAttribute/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingArrowAtributes"
        upperBound="-1" eType="#//ArrowAttribute" eOpposite="#//ArrowAttribute/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeDataNode" lowerBound="1"
        eType="#//DataNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" eType="#//DataType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datatype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeAttribute" eSuperTypes="#//IDObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/outgoingAttributes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeAttribute" lowerBound="1"
        eType="#//NodeAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" eOpposite="#//Constraint/nodeAttributes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//DataNode" eOpposite="#//DataNode/incomingNodeAttributes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrowAttribute" eSuperTypes="#//IDObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Arrow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeAttribute" lowerBound="1"
        eType="#//ArrowAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" eOpposite="#//Constraint/arrowAttributes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//DataNode" eOpposite="#//DataNode/incomingArrowAtributes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EEnum0"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass0">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//EClass1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass1"/>
  <eClassifiers xsi:type="ecore:EClass" name="EClass2" eSuperTypes="#//EClass0">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//EClass3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass3" eSuperTypes="#//EClass1"/>
</ecore:EPackage>
