/*
* generated by Xtext
*/
package no.hib.dpf.text.ui.contentassist;

import no.hib.dpf.text.ui.contentassist.AbstractDPFTextProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DPFTextProposalProvider extends AbstractDPFTextProposalProvider {

}
