<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="no"
    nsURI="http://no" nsPrefix="no">
  <eSubpackages name="hib" nsURI="http://no.hib" nsPrefix="no.hib">
    <eSubpackages name="dpf" nsURI="http://no.hib.dpf" nsPrefix="no.hib.dpf">
      <eSubpackages name="metamodel" nsURI="http://no.hib.dpf.metamodel" nsPrefix="no.hib.dpf.metamodel">
        <eClassifiers xsi:type="ecore:EClass" name="Graph" eSuperTypes="#//hib/dpf/metamodel/IDObject">
          <eOperations name="createNode" eType="#//hib/dpf/metamodel/Node">
            <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          </eOperations>
          <eOperations name="createEdge" eType="#//hib/dpf/metamodel/Edge">
            <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            <eParameters name="source" eType="#//hib/dpf/metamodel/Node"/>
            <eParameters name="target" eType="#//hib/dpf/metamodel/Node"/>
          </eOperations>
          <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
              eType="#//hib/dpf/metamodel/Node" containment="true" eOpposite="#//hib/dpf/metamodel/Node/graph"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
              eType="#//hib/dpf/metamodel/Edge" containment="true" eOpposite="#//hib/dpf/metamodel/Edge/graph"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//hib/dpf/metamodel/IDObject">
          <eOperations name="getOutgoingEdges" upperBound="-1" eType="#//hib/dpf/metamodel/Edge"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="#//hib/dpf/metamodel/Graph"
              eOpposite="#//hib/dpf/metamodel/Graph/nodes"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Edge" eSuperTypes="#//hib/dpf/metamodel/IDObject">
          <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//hib/dpf/metamodel/Node"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//hib/dpf/metamodel/Node"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="#//hib/dpf/metamodel/Graph"
              eOpposite="#//hib/dpf/metamodel/Graph/edges"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Signature">
          <eStructuralFeatures xsi:type="ecore:EReference" name="predicates" upperBound="-1"
              eType="#//hib/dpf/metamodel/Predicate" containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Predicate">
          <eStructuralFeatures xsi:type="ecore:EReference" name="shape" eType="#//hib/dpf/metamodel/Graph"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="semantics" eType="#//hib/dpf/metamodel/Semantics"
              containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="visualization" eType="#//hib/dpf/metamodel/Visualization"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Semantics"/>
        <eClassifiers xsi:type="ecore:EClass" name="Visualization" abstract="true"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeToNodeMap" instanceClassName="java.util.Map$Entry">
          <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//hib/dpf/metamodel/Node"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//hib/dpf/metamodel/Node"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Constraint">
          <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedModel"
              lowerBound="1" eType="#//hib/dpf/metamodel/Graph"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" eType="#//hib/dpf/metamodel/Predicate"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" eType="#//hib/dpf/metamodel/GraphHomomorphism"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="EdgeToEdgeMap" instanceClassName="java.util.Map$Entry">
          <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//hib/dpf/metamodel/Edge"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//hib/dpf/metamodel/Edge"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="TypingMorphism">
          <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1"
              eType="#//hib/dpf/metamodel/Graph"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="metamodel" lowerBound="1"
              eType="#//hib/dpf/metamodel/Graph"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" eType="#//hib/dpf/metamodel/GraphHomomorphism"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="GraphHomomorphism">
          <eStructuralFeatures xsi:type="ecore:EReference" name="nodeMapping" upperBound="-1"
              eType="#//hib/dpf/metamodel/NodeToNodeMap" containment="true"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="edgeMapping" upperBound="-1"
              eType="#//hib/dpf/metamodel/EdgeToEdgeMap" containment="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="IDObject">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
              defaultValueLiteral=""/>
        </eClassifiers>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
