/*
 * generated by Xtext
 */
package no.hib.dpf.text.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DPFTextExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return no.hib.dpf.text.ui.internal.DPFTextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return no.hib.dpf.text.ui.internal.DPFTextActivator.getInstance().getInjector("no.hib.dpf.text.DPFText");
	}
	
}
