/*
* generated by Xtext
*/
package no.hib.dpf.text.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class DPFTextOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
