<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rules">
  <eAnnotations source="EAnnotation0"/>
  <eAnnotations source="EAnnotation1"/>
  <eClassifiers xsi:type="ecore:EClass" name="2@ActivityGraph" eSuperTypes="#//1@StateMachine"/>
  <eClassifiers xsi:type="ecore:EClass" name="1@StateMachine"/>
  <eClassifiers xsi:type="ecore:EClass" name="A:{1,2}@StateMachine"/>
  <eClassifiers xsi:type="ecore:EClass" name="EClass0" instanceTypeName="ActivitGraph"/>
  <eClassifiers xsi:type="ecore:EClass" name="A:1@StateMachine"/>
  <eClassifiers xsi:type="ecore:EClass" name="A:{1,2}@StateMachine"/>
  <eClassifiers xsi:type="ecore:EClass" name="{1,2}@StateMachine"/>
  <eClassifiers xsi:type="ecore:EClass" name="{1,2}@StateMachine"/>
  <eClassifiers xsi:type="ecore:EClass" name="A:2@ActivityGraph"/>
  <eClassifiers xsi:type="ecore:EClass" name="1@Guard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="4@expression" lowerBound="1"
        eType="#//3@OpaqueExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="2@ActivityEdge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="5@guard" eType="#//1@Guard"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="6@guard" eType="#//3@OpaqueExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="3@OpaqueExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EClass1"/>
  <eClassifiers xsi:type="ecore:EClass" name="A:1@Guard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="D:4@expression" eType="#//C%3A3@OpaqueExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B:2@ActivityEdge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="E:5@guard" eType="#//A%3A1@Guard"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="F:6@guard" eType="#//C%3A3@OpaqueExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C:3@OpaqueExpression"/>
</ecore:EPackage>
