/*
 * generated by Xtext
 */
package no.hib.dpf.text.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DPFTextUiModule extends no.hib.dpf.text.ui.AbstractDPFTextUiModule {
	public DPFTextUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
