/*
* generated by Xtext
*/
package no.hib.dpf.text.ui.labeling;

import no.hib.dpf.text.tdpf.Arrow;
import no.hib.dpf.text.tdpf.ChoosenConstraintSemantic;
import no.hib.dpf.text.tdpf.ChoosenSpecification;
import no.hib.dpf.text.tdpf.Graph;
import no.hib.dpf.text.tdpf.Model;
import no.hib.dpf.text.tdpf.Node;
import no.hib.dpf.text.tdpf.Specification;
import no.hib.dpf.text.ui.Normalizer;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class DPFTextLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public DPFTextLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
		
	String text(Model m) {
		  return "Model";
	}

	String text(Specification n) {
	  if(null == n.getConstraintSemantic() || null == n.getConstraintSemantic().getId()){
		  return "Specification:" + n.getType().getId();
	  }else{
		  return "Specification:(" + n.getType().getId() + ", " + n.getConstraintSemantic().getId() + ")";		  
	  }
	}

	String text(ChoosenSpecification s) {
		  if(!"DPF".equals(s.getId())){
			  return "meta-specification=" + s.getId() + Normalizer.SPECIFICATION_FILE_EXTENSION;
		  }else{
			  return "meta-specification=DPF";
		  }
	}

	String text(Graph g) {
		  return "Graph";
	}
	
	
	String image(Node n) {
		  return "node.png";
	}

	String image(Arrow a) {
		  return "arrow.png";
	}	

	String image(Graph g) {
		  return "graph.png";
	}
	
	String image(Specification g) {
		  return "specification.png";
	}

	String text(ChoosenConstraintSemantic s) {
		  return "constraint-semantic=" + s.getId() + Normalizer.SIGNATURE_FILE_EXTENSION;
	}

}
