<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rules">
  <eClassifiers xsi:type="ecore:EClass" name="1@Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="5@top" lowerBound="1" eType="#//3@State"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="7@nodes" upperBound="-1"
        eType="#//2@ActivityNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="2@ActivityNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="3@State" eSuperTypes="#//2@ActivityNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="4@CompositeState" eSuperTypes="#//3@State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="6@subvertex" upperBound="-1"
        eType="#//2@ActivityNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composite" eSuperTypes="#//4@CompositeState"/>
  <eClassifiers xsi:type="ecore:EClass" name="A:1@Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="D:5@top" eType="#//B%3A4@CompositeState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="F:7@nodes" eType="#//C%3A2@ActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B:4@CompositeState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="E:6@subvertex" eType="#//C%3A2@ActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C:2@ActivityNode"/>
</ecore:EPackage>
